AddCSLuaFile()

TFA_YanKys_Realistic_Muzzleflashes = true
TFA.YanKys_Realistic_Muzzleflashes = TFA.YanKys_Realistic_Muzzleflashes or {}

if CLIENT then
	CreateClientConVar("cl_tfa_rms_default_eject_smoke", 0)
	CreateClientConVar("cl_tfa_rms_muzzleflash_dynlight", 1)
	CreateClientConVar("cl_tfa_rms_smoke_shock", 1)
	CreateClientConVar("fas2_flashes_dynlight", 0)

    game.AddParticles("particles/realistic_muzzleflashes_3.pcf")
end

if SERVER then
    game.AddParticles("particles/realistic_muzzleflashes_3.pcf")
end

PrecacheParticleSystem("muzzle_smoke_shock_small")
PrecacheParticleSystem("muzzle_smoke_shock_medium")
PrecacheParticleSystem("muzzle_smoke_shock_big")
PrecacheParticleSystem("muzzle_smoke_shock_suppressed")

PrecacheParticleSystem("muzzleflash_pistol")
PrecacheParticleSystem("muzzleflash_pistol_red")
PrecacheParticleSystem("muzzleflash_pistol_deagle")
PrecacheParticleSystem("muzzleflash_pistol_rbull")
PrecacheParticleSystem("muzzleflash_makarov")
PrecacheParticleSystem("muzzleflash_ots")
PrecacheParticleSystem("muzzleflash_pernach")
PrecacheParticleSystem("muzzleflash_g21c")
PrecacheParticleSystem("muzzleflash_m1911")
PrecacheParticleSystem("muzzleflash_smg")
PrecacheParticleSystem("muzzleflash_smg_bizon")
PrecacheParticleSystem("muzzleflash_mp5")
PrecacheParticleSystem("muzzleflash_mpx")
PrecacheParticleSystem("muzzleflash_p90")
PrecacheParticleSystem("muzzleflash_ppsh")
PrecacheParticleSystem("muzzleflash_1")
PrecacheParticleSystem("muzzleflash_2")
PrecacheParticleSystem("muzzleflash_3")
PrecacheParticleSystem("muzzleflash_4")
PrecacheParticleSystem("muzzleflash_5")
PrecacheParticleSystem("muzzleflash_6")
PrecacheParticleSystem("muzzleflash_ak47")
PrecacheParticleSystem("muzzleflash_ak74")
PrecacheParticleSystem("muzzleflash_ak103")
PrecacheParticleSystem("muzzleflash_an94")
PrecacheParticleSystem("muzzleflash_acr")
PrecacheParticleSystem("muzzleflash_famas")
PrecacheParticleSystem("muzzleflash_ash12")
PrecacheParticleSystem("muzzleflash_m14")
PrecacheParticleSystem("muzzleflash_g3")
PrecacheParticleSystem("muzzleflash_fal")
PrecacheParticleSystem("muzzleflash_scarh")
PrecacheParticleSystem("muzzleflash_shotgun")
PrecacheParticleSystem("muzzleflash_slug")
PrecacheParticleSystem("muzzleflash_m3")
PrecacheParticleSystem("muzzleflash_sniper")
PrecacheParticleSystem("muzzleflash_awm")
PrecacheParticleSystem("muzzleflash_m24")
PrecacheParticleSystem("muzzleflash_sr25")
PrecacheParticleSystem("muzzleflash_svd")
PrecacheParticleSystem("muzzleflash_sv98")
PrecacheParticleSystem("muzzleflash_m82")
PrecacheParticleSystem("muzzleflash_minimi")
PrecacheParticleSystem("muzzleflash_vollmer")
PrecacheParticleSystem("muzzleflash_m79")
PrecacheParticleSystem("muzzleflash_suppressed")

PrecacheParticleSystem("muzzleflash_npc_pistol")
PrecacheParticleSystem("muzzleflash_npc_smg")
PrecacheParticleSystem("muzzleflash_npc_shotgun")
PrecacheParticleSystem("muzzleflash_npc_rifle")
PrecacheParticleSystem("muzzleflash_npc_sniper")