AddCSLuaFile()

VManip:RegisterAnim("swimforward",
{
["model"]="c_vmanip.mdl",
["lerp_peak"]=1.4,
["lerp_speed_in"]=1,
["lerp_speed_out"]=0.8,
["lerp_curve"]=1,
["speed"]=0.6,
["startcycle"]=0,
["sounds"]={},
["loop"]=true
}
)

VManip:RegisterAnim("swimleft",
{
["model"]="c_vmanip.mdl",
["lerp_peak"]=1.4,
["lerp_speed_in"]=1,
["lerp_speed_out"]=0.8,
["lerp_curve"]=1,
["speed"]=0.6,
["startcycle"]=0,
["sounds"]={},
["loop"]=true
}
)

VManip:RegisterAnim("shieldexplosion",
{
["model"]="weapons/c_handanims.mdl",
["lerp_peak"]=1.25,
["lerp_speed_in"]=0.65,
["lerp_speed_out"]=0.95,
["lerp_curve"]=1.75,
["speed"]=0.5,
["startcycle"]=0.02,
["cam_angint"]={1,0.25,0.5},
["loop"]=false
--["holdtime"]=nil
}
)

VManip:RegisterAnim("barnaclechoke",
{
["model"]="weapons/c_handanims.mdl",
["lerp_peak"]=0.3,
["lerp_speed_in"]=0.65,
["lerp_speed_out"]=0.95,
["lerp_curve"]=1.75,
["speed"]=1.5,
["startcycle"]=0.02,
["cam_angint"]={1,0.25,0.5},
["loop"]=false,
["holdtime"]=0.2
}
)

VManip:RegisterAnim("voicechat",
{
["model"]="weapons/c_handanims.mdl",
["lerp_peak"]=0.3,
["lerp_speed_in"]=0.65,
["lerp_speed_out"]=0.95,
["lerp_curve"]=1.25,
["speed"]=2.5,
["startcycle"]=0,
["cam_angint"]={0.01,0.01,0.05},
["loop"]=false,
["holdtime"]=0.21,
["locktoply"]=true
}
)